version: "3"
services:
  mysql:
    image: mysql:latest
    ports:
      - 3305:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challenge
  redis:
    restart: always
    image: redis:4.0
    container_name: redis-server
    command: /bin/bash -c 'redis-server --appendonly yes'
    sysctls:
      - net.core.somaxconn=65535
    ports:
      - "6378:6379"
    volumes:
      - ./redis:/data
    mem_limit: 96m